### ISSUE TITLE
How to install haconfig files?

### ISSUE THREAD

**Issue by panosnl** [vekexasia/comfoair-esp32#22]
Hi,

I have the comfoair to mqtt running but now I have problems getting the haconfig file properly integrated in HA.

I tried !include index.yaml in the configuration.yaml but that seemed not to work: vmc_comfoair: is not an integration . Also it does not seem like a custom component either or is it?

index.yaml 

vmc_comfoair:
  sensor: !include ./.sensors.yaml
  input_select:
    vmc_user_fan_speed:
      name: "VMC User Fan Speed"
      options:
        - "0"
        - "1"
        - "2"
        - "3"
    vmc_operating_mode:
      name: "VMC User Mode"
      options:
        - auto
        - manual
  automation: !include ./.automations.yaml
  switch: !include ./.switch.yaml

**Comment by J1Buskens** [comment]
How did you fix it?

**Comment by panosnl** [comment]
> How did you fix it?

I was new to HA so the 'manual' on github was not clear to me and also syntax seemed outdated. 
Eventually i got it working using the following settings

in configuration.yaml:

```
mqtt: !include mqtt.yaml
switch:
- platform: template
  switches:
    vmc_supply_ventilation:
      value_template: "{{ states('sensor.vmc_supply_fan_duty') | int > 0 }}"
      turn_on:
        service: mqtt.publish
        data:
          topic: comfoair/commands/ventilation_extract_only_reset
          payload: ':)'
      turn_off:
        service: mqtt.publish
        data:
          topic: comfoair/commands/ventilation_extract_only
          payload: ':)'

    vmc_extract_ventilation:
      value_template: "{{ states('sensor.vmc_exhaust_fan_duty') | int > 0 }}"
      turn_on:
        service: mqtt.publish
        data:
          topic: comfoair/commands/ventilation_supply_only_reset
          payload: ':)'
      turn_off:
        service: mqtt.publish
        data:
          topic: comfoair/commands/ventilation_supply_only
          payload: ':)'
```

in automations.yaml:
```
- id: Comfoair1
  alias: Comfoair nacht op 1
  description: ''
  trigger:
  - at: 00:00:00
    platform: time
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: comfoair/commands/ventilation_level_1
      payload: true
- id: Comfoair2
  alias: '[VMC] Auto Update user fan speed from MQTT'
  trigger:
    platform: mqtt
    topic: comfoair/fan_speed
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.vmc_user_fan_speed
      option: '{{ trigger.payload }}'
- id: Comfoair3
  alias: '[VMC] Set user fan speed on VMC from input select'
  trigger:
  - platform: state
    entity_id:
    - input_select.vmc_user_fan_speed
  action:
  - service: mqtt.publish
    data:
      topic: comfoair/commands/ventilation_level
      payload: '{{ states(''input_select.vmc_user_fan_speed'') }}'
- id: Comfoair4
  alias: '[VMC] Auto Update user operation mode from MQTT'
  trigger:
    platform: mqtt
    topic: comfoair/operating_mode
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.vmc_operating_mode
      option: '{{ ''manual'' if trigger.payload != ''auto'' else ''auto''}}'
- id: Comfoair5
  alias: '[VMC] Set user operating mode on VMC from input select'
  trigger:
    platform: state
    entity_id: input_select.vmc_operating_mode
  action:
  - service: mqtt.publish
    data:
      topic: comfoair/commands/set_mode
      payload: '{{ states(''input_select.vmc_operating_mode'') }}'
```

mqtt.yaml

```
#mqtt:
  sensor:    
    # Consumption
    - name: "VMC Power Current"
      unique_id: "VMC Power Current"
      state_topic: "comfoair/power_consumption_current"
      unit_of_measurement: W
    - name: "VMC Total Energy Saving"
      unique_id: "VMC Total Energy Saving"
      state_topic: "comfoair/ah_ytd"
      unit_of_measurement: Wh
    
    # FAns
    - name: "VMC Exhaust Fan Speed"
      unique_id: "VMC Exhaust Fan Speed"
      state_topic: "comfoair/exhaust_fan_speed"
      unit_of_measurement: rpm
    - name: "VMC Supply Fan Speed"
      unique_id: "VMC Supply Fan Speed"
      state_topic: "comfoair/supply_fan_speed"
      unit_of_measurement: rpm
    - name: "VMC Exhaust Fan Duty"
      unique_id: "VMC Exhaust Fan Duty"
      state_topic: "comfoair/exhaust_fan_duty"
      unit_of_measurement: rpm
    - name: "VMC Supply Fan Duty"
      unique_id: "VMC Supply Fan Duty"
      state_topic: "comfoair/supply_fan_duty"
      unit_of_measurement: rpm
    - name: "VMC Supply Fan User Speed"
      unique_id: "VMC Supply Fan User Speed"
      state_topic: "comfoair/fan_speed"
    
      # FLOW
    - name: "VMC Exhaust Fan Flow"
      unique_id: "VMC Exhaust Fan Flow"
      state_topic: "comfoair/exhaust_fan_flow"
      unit_of_measurement: "m³/h"
    - name: "VMC Supply Fan Flow"
      unique_id: "VMC Supply Fan Flow"
      state_topic: "comfoair/supply_fan_flow"
      unit_of_measurement: "m³/h"
    
    # TEMPS
    - name: "VMC Outdoor Air Temperature"
      unique_id: "VMC Outdoor Air Temperature"
      state_topic: "comfoair/outdoor_air_temp"
      unit_of_measurement: "°C"
    - name: "VMC Exhaust Air Temperature"
      unique_id: "VMC Exhaust Air Temperature"
      state_topic: "comfoair/exhaust_air_temp"
      unit_of_measurement: "°C"
    - name: "VMC Extract Air Temperature"
      unique_id: "VMC Extract Air Temperature"
      state_topic: "comfoair/extract_air_temp"
      unit_of_measurement: "°C"
    - name: "VMC Pre Heater Temp Before"
      unique_id: "VMC Pre Heater Temp Before"
      state_topic: "comfoair/pre_heater_temp_before"
      unit_of_measurement: "°C"
    - name: "VMC Pre Heater Temp After"
      unique_id: "VMC Pre Heater Temp After"
      state_topic: "comfoair/pre_heater_temp_after"
      unit_of_measurement: "°C"
    - name: "VMC Post Heater Temp Before"
      unique_id: "VMC Post Heater Temp Before"
      state_topic: "comfoair/post_heater_temp_before"
      unit_of_measurement: "°C"
    - name: "VMC Post Heater Temp After"
      unique_id: "VMC Post Heater Temp After"
      state_topic: "comfoair/post_heater_temp_after"
      unit_of_measurement: "°C"
   
    # Humidity
    - name: "VMC Outdoor Air Humidity"
      unique_id: "VMC Outdoor Air Humidity"
      state_topic: "comfoair/outdoor_air_humidity"
      unit_of_measurement: "%"
    - name: "VMC Exhaust Air Humidity"
      unique_id: "VMC Exhaust Air Humidity"
      state_topic: "comfoair/exhaust_air_humidity"
      unit_of_measurement: "%"
    - name: "VMC Extract Air Humidity"
      unique_id: "VMC Extract Air Humidity"
      state_topic: "comfoair/extract_air_humidity"
      unit_of_measurement: "%"
    - name: "VMC Supply Air Humidity"
      unique_id: "VMC Supply Air Humidity"
      state_topic: "comfoair/supply_air_humidity"
      unit_of_measurement: "%"
```

Note that fan parameters are updated every second making my HA database very slow so I excluded these from the database

```
recorder:
  exclude:
    entities:
      - sensor.vmc_exhaust_fan_duty
      - sensor.vmc_exhaust_fan_flow
      - sensor.vmc_exhaust_fan_speed
      - sensor.vmc_supply_fan_duty
      - sensor.vmc_supply_fan_flow
      - sensor.vmc_supply_fan_speed
```
