### ISSUE TITLE
Button for mqtt commands

### ISSUE THREAD

**Issue by pyzimmer** [vekexasia/comfoair-esp32#45]
Here is part of configuration.yaml to get command buttons in HA : 
```
mqtt:
  button:
    - name: "VMC Boost 1h"
      command_topic: "comfoair/commands/boost_60_min"
    - name: "VMC Boost Stop"
      command_topic: "comfoair/commands/boost_end"     
    - name: "VMC Bypass ON 1h"
      command_topic: "comfoair/commands/bypass_activate_1h"     
    - name: "VMC Bypass OFF 1h"
      command_topic: "comfoair/commands/bypass_deactivate_1h"     
    - name: "VMC Bypass AUTO"
      command_topic: "comfoair/commands/bypass_auto"     
    - name: "VMC Profile Normal"
      command_topic: "comfoair/commands/temp_profile_normal"     
    - name: "VMC Profile Cool"
      command_topic: "comfoair/commands/temp_profile_cool"     
    - name: "VMC Profile Warm"
      command_topic: "comfoair/commands/temp_profile_warm"     
```

the result : 
![image](https://user-images.githubusercontent.com/43472705/220930518-32546d87-c7d4-49cd-9002-f29b26010bbb.png)
