### ISSUE TITLE
ESPHome 2023.10.5 & comfoair-eps32 error in compile

### ISSUE THREAD

**Issue by tudstudent** [vekexasia/comfoair-esp32#60]
While digging into the esphome component I tried to compile. Whenever I add the connection pins the compilation will stop running with the following error:

```
Compiling .pioenvs\esp32-mqtt-zehnder-kd\libd8f\noise-c\protocol\symmetricstate.c.o
Compiling .pioenvs\esp32-mqtt-zehnder-kd\libd8f\noise-c\protocol\util.c.o
Compiling .pioenvs\esp32-mqtt-zehnder-kd\lib760\SPI\SPI.cpp.o
Compiling .pioenvs\esp32-mqtt-zehnder-kd\lib117\can_common\can_common.cpp.o
Compiling .pioenvs\esp32-mqtt-zehnder-kd\lib58d\esp32_can\esp32_can.cpp.o
Compiling .pioenvs\esp32-mqtt-zehnder-kd\lib58d\esp32_can\esp32_can_builtin.cpp.o
Compiling .pioenvs\esp32-mqtt-zehnder-kd\lib58d\esp32_can\esp32_can_builtin_lowlevel.cpp.o
Compiling .pioenvs\esp32-mqtt-zehnder-kd\lib58d\esp32_can\mcp2515.cpp.o
Compiling .pioenvs\esp32-mqtt-zehnder-kd\lib58d\esp32_can\mcp2517fd.cpp.o
Archiving .pioenvs\esp32-mqtt-zehnder-kd\libd8f\libnoise-c.a
Archiving .pioenvs\esp32-mqtt-zehnder-kd\lib760\libSPI.a
In file included from .piolibdeps/esp32-mqtt-zehnder-kd/esp32_can/src/esp32_can_builtin_lowlevel.cpp:32:
C:/Users/folderXXX/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/esp_hw_support/include/esp_intr.h:8:2: warning: #warning esp_intr.h is deprecated, please include esp_intr_alloc.h instead [-Wcpp]
 #warning esp_intr.h is deprecated, please include esp_intr_alloc.h instead
  ^~~~~~~
.piolibdeps/esp32-mqtt-zehnder-kd/esp32_can/src/esp32_can_builtin_lowlevel.cpp:33:10: fatal error: soc/dport_reg.h: No such file or directory
 #include "soc/dport_reg.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pioenvs\esp32-mqtt-zehnder-kd\FrameworkArduino\Esp.cpp.o
*** [.pioenvs\esp32-mqtt-zehnder-kd\lib58d\esp32_can\esp32_can_builtin_lowlevel.cpp.o] Error 1
========================= [FAILED] Took 49.27 seconds =========================
```

The config used:

```
esphome:
  name: esp32-mqtt-zehnder-kd
  friendly_name: ESP32 MQTT Zehnder ComfoAir Q600 Kelder

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXYYYYYZZZZZ"

ota:
  password: "XXXXXYYYYYZZZZZ"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

#captive_portal:

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Amsterdam
    servers: 192.168.0.1

external_components:
  - source: github://vekexasia/comfoair-esp32
    components: [ comfoair ]

comfoair:
  id: comfo
  rx_pin: GPIO5
  tx_pin: GPIO2
```

Pins are correct as I use the same device also for other applications (same RX and TX pins)
And lastly, posting it here as the error emerges only after enabling the comfoair module.
(Therefore might still be an issue with the esphome software, in that case please inform me so I will redirect the answer)
