### ISSUE TITLE
GPIO configuration for D1 Mini ESP32

### ISSUE THREAD

**Issue by st1234b** [vekexasia/comfoair-esp32#65]
I am using a D1 Mini ESP32. 
![Screenshot 2024-01-12 110132](https://github.com/vekexasia/comfoair-esp32/assets/135973926/9ebc5633-ac00-4de3-8924-ef141d40e024)

https://cdn.shopify.com/s/files/1/1509/1638/files/D1_Mini_ESP32_-_pinout.pdf
https://www.amazon.de/AZDelivery-Bluetooth-Internet-Entwicklungsboard-kompatibel/dp/B08BTLYSTM

What should the configuration in ESPHome look like for GPIO 1 (RX) and GPIO 3 (TX)?
The default configuration is as follows, what do I need to add?

```
external_components:
  - source: github://vekexasia/comfoair-esp32
    components: [ comfoair ]

comfoair:

```
